---

- name: Add Cumulus Apt Key
  apt_key:
    url: https://apps3.cumulusnetworks.com/setup/cumulus-apps-deb.pubkey
    state: present
  when: netq_installed.stdout.find('[installed]') == -1

- name: Add Cumulus Repo - roh-3
  apt_repository:
    repo: deb [arch=amd64] https://apps3.cumulusnetworks.com/repos/deb xenial roh-3
    state: present
    update_cache: no
  when: netq_installed.stdout.find('[installed]') == -1

- name: Install FRR
  apt:
    name: frr
    update_cache: yes

- name: Copy FRR daemons file
  copy:
    src: daemons
    dest: /etc/frr/daemons
    backup: yes
  notify: restart frr

- name: Copy interfaces configuration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    backup: yes
  notify: reload networking

- name: Copy FRR configuration
  template:
    src: frr.j2
    dest: /etc/frr/frr.conf
    backup: yes
  notify: restart frr

- name: Bring up eth1 interface
  command: "ifup {{item}}"
  with_items:
    - eth1
