---

- name: Configured NTP in management VRF
  command: "{{item}}"
  with_items:
    - systemctl stop ntp.service
    - systemctl disable ntp.service
    - systemctl start ntp@mgmt

- name: Add Cumulus Repo
  apt_repository:
    repo: deb https://apps3.cumulusnetworks.com/repos/deb CumulusLinux-3 netq-1.3
    state: present
    update_cache: yes

- name: Install NetQ 1.3
  command: apt-get -y --allow-unauthenticated install cumulus-netq

- name: Enable NetQ Service
  service:
    name: netqd
    enabled: yes
    state: started

- name: Pause to let NetQ service to start
  pause:
    seconds: 5

- name: Add netq server IP
  command: netq config add server 192.168.200.254 vrf mgmt

- name: Restart NetQ Agent
  command: netq config restart agent
