---

- name: Add Cumulus Apt Key
  apt_key:
    url: "https://apps3.cumulusnetworks.com/setup/cumulus-apps-deb.pubkey"
    state: present

- name: Add Cumulus Repo
  apt_repository:
    repo: deb http://apps3.cumulusnetworks.com/repos/deb CumulusLinux-3 netq-latest
    state: present
    update_cache: yes

- name: Install NetQ
  apt:
    name: cumulus-netq
    state: latest

- name: Pause to let NetQ service to start
  pause:
    seconds: 5

- name: Restart Rsyslog
  service:
    name: rsyslog
    state: restarted

- name: Add netq server IP
  command: netq config add server 192.168.200.250 vrf mgmt

- name: Restart NetQ Agent
  command: netq config restart agent

- name: reboot
  reboot:
    pre_reboot_delay: 60
