---
- name: restart LLDP
  service:
    name: lldpd
    state: restarted

- name: restart NTPD
  service:
    name: ntp
    state: restarted

# - name: reload networking
#  command: "ifreload -a"

- name: reload networking
  service:
    name: networking
    state: reloaded

- name: restart frr
  service:
    name: frr
    state: restarted

- name: reload frr
  service:
    name: frr
    state: reloaded
