---

- name: Check NetQ install
  command: apt search cumulus-netq
  register: netq_installed

- name: Add Cumulus Apt Key
  apt_key:
    url: https://apps3.cumulusnetworks.com/setup/cumulus-apps-deb.pubkey
    state: present

- name: Add Cumulus Repo - netq-latest
  apt_repository:
    repo: deb [arch=amd64] https://apps3.cumulusnetworks.com/repos/deb xenial netq-latest
    state: present
    update_cache: yes

- name: Add Cumulus Repo - roh-3
  apt_repository:
    repo: deb [arch=amd64] https://apps3.cumulusnetworks.com/repos/deb xenial roh-3
    state: present
    update_cache: yes

- name: Install LLDPd
  apt:
    name: lldpd

- name: Correct LLDP Settings
  lineinfile:
    dest: /etc/lldpd.d/port_info.conf
    line: "configure lldp portidsubtype ifname"
    create: yes
  notify: restart LLDP

- name: Apply LLDP Settings
  meta: flush_handlers

- name: Install ntp
  apt:
    name: ntp
  notify: restart NTPD

- name: Install NetQ
  apt:
    name: cumulus-netq
    state: latest

- name: Configure NetQ
  command: "{{item}}"
  with_items:
    - systemctl stop netqd.service
    - systemctl start netqd.service
    - systemctl stop netq-agent.service
    - systemctl start netq-agent.service

- name: Add netq server IP
  command: netq config add server 192.168.200.250

- name: Pause to let NetQ service to start
  pause:
    seconds: 5

- name: NetQ config add stats
  command: netq config add agent stats

- name: Restart Rsyslog
  service:
    name: rsyslog
    state: restarted

- name: Restart NetQ Agent
  command: netq config restart agent

- name: Pause to let NetQ service to start
  pause:
    seconds: 5
