---
# Ping script is so servers generate traffic to populate MAC tables
# - name: Configure Server01 Ping Cronjob
#  cron:
#    name: "server ping"
#    job: "ping -c 1 10.1.3.103"
#  become: yes
#  become_user: cumulus
#  when: inventory_hostname == "server01"

#- name: Configure Server02 Ping Cronjob
#  cron:
#    name: "server ping"
#    job: "ping -c 1 10.2.4.104"
#  become: yes
#  become_user: cumulus
#  when: inventory_hostname == "server02"

- name: Correct LLDP Settings
  lineinfile:
    dest: /etc/lldpd.d/port_info.conf
    line: "configure lldp portidsubtype ifname"
    create: yes
  notify: restart LLDP

- name: Apply LLDP Settings
  meta: flush_handlers

- name: Add Cumulus Apt Key
  apt_key:
    url: "https://apps3.cumulusnetworks.com/setup/cumulus-apps-deb.pubkey"
    state: present

- name: Install Python-Apt
  apt:
    name: python-apt
    update_cache: yes

- name: Add Cumulus Repo
  apt_repository:
    repo: deb https://apps3.cumulusnetworks.com/repos/deb xenial netq-1.3
    state: present
    update_cache: no

- name: Install NetQ
  apt:
    name: cumulus-netq
    update_cache: yes
  register: install-netq

- name: Restart Rsyslog
  service:
    name: rsyslog
    state: restarted

- name: Enable NetQ Service
  service:
    name: netqd
    enabled: yes
    state: started

- name: Pause to let NetQ service to start
  pause:
    seconds: 5

- name: Add netq server IP
  command: netq config add server 192.168.0.254

- name: Restart NetQ Agent
  command: netq config restart agent

- name: reboot
  command: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true

- name: Sleep for server to disconnect
  pause:
    seconds: 10

- name: Wait for hosts to be up
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    delay: 30
    timeout: 300
  ignore_errors: true
