#####
# Host config for int-ansible-training-l3-dc-hostpack-j2
#####

- hosts: switches
  become: true
  roles:
  - switches
#  - netqHosts

- hosts: servers
  become: true
  roles:
  - servers
  - netqServer
